// GENERATED by scripts/gen-authz.mjs from the project's OpenAPI contracts
// (specs/design/components/*/openapi.yaml and
// specs/design/components/*/dependencies/*.openapi.yaml).
// Do not edit by hand, and do not retype any of these values anywhere else.
// Re-run `npm run gen` after a contract changes. COMMIT this file: the
// per-component image build cannot see the specs tree.
//
// This table is what a screen is gated on. src/authz/screens.ts names the
// operation each screen LOADS; holding that operation's scope is what makes the
// screen reachable. Nothing else in the app decides that.

import type { Scope } from "./roles.gen";

/** What the gateway demands of a caller before it will pass an operation on. */
export type OperationRequirement =
  | { readonly kind: "public" }
  | { readonly kind: "signedIn" }
  | { readonly kind: "scope"; readonly scope: Scope };

/** "<METHOD> <path template>" as the contract spells it, e.g. "GET /me/claims". Sorted. */
export type OperationKey =
  | "DELETE /me/claims/{claimId}"
  | "DELETE /me/claims/{claimId}/lines/{lineId}"
  | "GET /categories"
  | "GET /claims"
  | "GET /claims/exports"
  | "GET /claims/exports/{exportId}"
  | "GET /claims/receipts/{receiptId}"
  | "GET /claims/{claimId}"
  | "GET /health"
  | "GET /me/claims"
  | "GET /me/claims/{claimId}"
  | "GET /me/claims/{claimId}/lines/{lineId}/receipt"
  | "GET /me/notifications"
  | "GET /me/reports/claims"
  | "GET /me/reports/claims/{claimId}"
  | "GET /me/reports/receipts/{receiptId}"
  | "GET /people"
  | "POST /claims/exports"
  | "POST /claims/{claimId}/approve"
  | "POST /claims/{claimId}/return"
  | "POST /me/claims"
  | "POST /me/claims/{claimId}/lines"
  | "POST /me/claims/{claimId}/lines/{lineId}/receipt"
  | "POST /me/claims/{claimId}/submit"
  | "POST /me/reports/claims/{claimId}/approve"
  | "POST /me/reports/claims/{claimId}/return"
  | "PUT /me/claims/{claimId}"
  | "PUT /me/claims/{claimId}/lines/{lineId}";

export const OPERATIONS: Record<OperationKey, OperationRequirement> = {
  "DELETE /me/claims/{claimId}": { kind: "scope", scope: "claims:write" },
  "DELETE /me/claims/{claimId}/lines/{lineId}": { kind: "scope", scope: "claims:write" },
  "GET /categories": { kind: "public" },
  "GET /claims": { kind: "scope", scope: "claims:review-all" },
  "GET /claims/exports": { kind: "scope", scope: "claims:export" },
  "GET /claims/exports/{exportId}": { kind: "scope", scope: "claims:export" },
  "GET /claims/receipts/{receiptId}": { kind: "scope", scope: "claims:review-all" },
  "GET /claims/{claimId}": { kind: "scope", scope: "claims:review-all" },
  "GET /health": { kind: "public" },
  "GET /me/claims": { kind: "scope", scope: "claims:read" },
  "GET /me/claims/{claimId}": { kind: "scope", scope: "claims:read" },
  "GET /me/claims/{claimId}/lines/{lineId}/receipt": { kind: "scope", scope: "claims:read" },
  "GET /me/notifications": { kind: "signedIn" },
  "GET /me/reports/claims": { kind: "scope", scope: "claims:review" },
  "GET /me/reports/claims/{claimId}": { kind: "scope", scope: "claims:review" },
  "GET /me/reports/receipts/{receiptId}": { kind: "scope", scope: "claims:review" },
  "GET /people": { kind: "signedIn" },
  "POST /claims/exports": { kind: "scope", scope: "claims:export" },
  "POST /claims/{claimId}/approve": { kind: "scope", scope: "claims:export" },
  "POST /claims/{claimId}/return": { kind: "scope", scope: "claims:export" },
  "POST /me/claims": { kind: "scope", scope: "claims:write" },
  "POST /me/claims/{claimId}/lines": { kind: "scope", scope: "claims:write" },
  "POST /me/claims/{claimId}/lines/{lineId}/receipt": { kind: "scope", scope: "claims:write" },
  "POST /me/claims/{claimId}/submit": { kind: "scope", scope: "claims:submit" },
  "POST /me/reports/claims/{claimId}/approve": { kind: "scope", scope: "claims:approve" },
  "POST /me/reports/claims/{claimId}/return": { kind: "scope", scope: "claims:approve" },
  "PUT /me/claims/{claimId}": { kind: "scope", scope: "claims:write" },
  "PUT /me/claims/{claimId}/lines/{lineId}": { kind: "scope", scope: "claims:write" },
};

export function isOperationKey(value: string): value is OperationKey {
  return Object.prototype.hasOwnProperty.call(OPERATIONS, value);
}
